// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3K-CwJdEMZt8K8prtBEN88UchmiTtf8s',
    appId: '1:399453062734:web:4e4a28ab42e1d77bbee51f',
    messagingSenderId: '399453062734',
    projectId: 'chatbuddy-53d07',
    authDomain: 'chatbuddy-53d07.firebaseapp.com',
    databaseURL: 'https://chatbuddy-53d07-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-53d07.appspot.com',
    measurementId: 'G-V84V0KC7EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgZgHV2jnZO2Bq-VtVPSbThJjbuZyyBI',
    appId: '1:399453062734:android:df5bb12fa3c64de6bee51f',
    messagingSenderId: '399453062734',
    projectId: 'chatbuddy-53d07',
    databaseURL: 'https://chatbuddy-53d07-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-53d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJhqwaL1Ay01lrYHifJiaFk6ouzmvB9o',
    appId: '1:399453062734:ios:a56ad1f9ba5a518dbee51f',
    messagingSenderId: '399453062734',
    projectId: 'chatbuddy-53d07',
    databaseURL: 'https://chatbuddy-53d07-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-53d07.appspot.com',
    iosBundleId: 'com.example.chatBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADJhqwaL1Ay01lrYHifJiaFk6ouzmvB9o',
    appId: '1:399453062734:ios:73b2f9d5f6003f9fbee51f',
    messagingSenderId: '399453062734',
    projectId: 'chatbuddy-53d07',
    databaseURL: 'https://chatbuddy-53d07-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-53d07.appspot.com',
    iosBundleId: 'com.example.chatBuddy.RunnerTests',
  );
}
