// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0VmMG9FFY1Wc8135xdfVkUUxk3wgFt4',
    appId: '1:322955723978:web:3809ef9adbdb1ad1756033',
    messagingSenderId: '322955723978',
    projectId: 'huskychat-6ccec',
    authDomain: 'huskychat-6ccec.firebaseapp.com',
    storageBucket: 'huskychat-6ccec.appspot.com',
    measurementId: 'G-RKRE82H55K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6uehxTNYwjSK8q9-dOi2PNQK9UCLS4c',
    appId: '1:322955723978:android:9e85532f8e819285756033',
    messagingSenderId: '322955723978',
    projectId: 'huskychat-6ccec',
    storageBucket: 'huskychat-6ccec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbh68GkQrcZdclZGy7NyG4Zh1g20npXts',
    appId: '1:322955723978:ios:bb0af5d94a073e2f756033',
    messagingSenderId: '322955723978',
    projectId: 'huskychat-6ccec',
    storageBucket: 'huskychat-6ccec.appspot.com',
    iosBundleId: 'com.example.huskyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbh68GkQrcZdclZGy7NyG4Zh1g20npXts',
    appId: '1:322955723978:ios:f34f2f23eb43cb46756033',
    messagingSenderId: '322955723978',
    projectId: 'huskychat-6ccec',
    storageBucket: 'huskychat-6ccec.appspot.com',
    iosBundleId: 'com.example.huskyChat.RunnerTests',
  );
}
