// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe5hzYQk8IUk_CND3A6xbzOLwyIzt3fPc',
    appId: '1:935744333992:web:7b578f86e20f5859eafa9d',
    messagingSenderId: '935744333992',
    projectId: 'pandatalks-2c970',
    authDomain: 'pandatalks-2c970.firebaseapp.com',
    databaseURL: 'https://pandatalks-2c970-default-rtdb.firebaseio.com',
    storageBucket: 'pandatalks-2c970.appspot.com',
    measurementId: 'G-NY85195NLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkZ1qJzZZkqCjbmxPJ0JRh6-Sdv3gCkE',
    appId: '1:935744333992:android:5555072e718b83eeeafa9d',
    messagingSenderId: '935744333992',
    projectId: 'pandatalks-2c970',
    databaseURL: 'https://pandatalks-2c970-default-rtdb.firebaseio.com',
    storageBucket: 'pandatalks-2c970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkF5mAJlAQW8j0n_shjrCOnPEeyHca5KA',
    appId: '1:935744333992:ios:52d9e8a9f8640306eafa9d',
    messagingSenderId: '935744333992',
    projectId: 'pandatalks-2c970',
    databaseURL: 'https://pandatalks-2c970-default-rtdb.firebaseio.com',
    storageBucket: 'pandatalks-2c970.appspot.com',
    iosBundleId: 'com.example.pandaTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkF5mAJlAQW8j0n_shjrCOnPEeyHca5KA',
    appId: '1:935744333992:ios:50f1604f331d85c2eafa9d',
    messagingSenderId: '935744333992',
    projectId: 'pandatalks-2c970',
    databaseURL: 'https://pandatalks-2c970-default-rtdb.firebaseio.com',
    storageBucket: 'pandatalks-2c970.appspot.com',
    iosBundleId: 'com.example.pandaTalks.RunnerTests',
  );
}
