// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwX--luNyCHBB-z2nYUWR6A0i7PvgLQgM',
    appId: '1:258442290276:web:202fbb6ae2b90803cf2b71',
    messagingSenderId: '258442290276',
    projectId: 'dating-app-25563',
    authDomain: 'dating-app-25563.firebaseapp.com',
    storageBucket: 'dating-app-25563.appspot.com',
    measurementId: 'G-E6HPHXZECJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAI-Q_sZwnQJ_QZoJ4kc1EA4_CWo1SEc',
    appId: '1:258442290276:android:8aa9b2aae37056a5cf2b71',
    messagingSenderId: '258442290276',
    projectId: 'dating-app-25563',
    storageBucket: 'dating-app-25563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVK82DGkiQwwPDMyu8QlJrN8rWReHgwaw',
    appId: '1:258442290276:ios:b47f41e2539a09eecf2b71',
    messagingSenderId: '258442290276',
    projectId: 'dating-app-25563',
    storageBucket: 'dating-app-25563.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVK82DGkiQwwPDMyu8QlJrN8rWReHgwaw',
    appId: '1:258442290276:ios:cf38b123240a59b0cf2b71',
    messagingSenderId: '258442290276',
    projectId: 'dating-app-25563',
    storageBucket: 'dating-app-25563.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
